import { Poppins } from "next/font/google";
import "./globals.css";
import SessionTracker from "@/components/SessionTracker";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
      </head>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <SessionTracker />
        {children}
      </body>
    </html>
  );
}